config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :questions, param: :slug

  devise_for :users,
             path: '',
             path_names: {
               sign_in: 'login',
               password: 'forgot',
               confirmation: 'confirm',
               unlock: 'unblock',
               sign_up: 'register',
               sign_out: 'logout'
             }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :replies

  after_validation :generate_slug

  has_rich_text :body

  paginates_per 20

  default_scope { includes(:user, :category) }
  scope :with_replies, -> { includes(:replies) }

  def generate_slug
    self.slug = title.parameterize
  end

  def to_param
    slug
  end
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = %i[username email password password_confirmation remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @questions = Question.page params[:page]
  end

  def about
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show; end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit; end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user = current_user

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.with_replies.find_by slug: params[:slug]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def question_params
    params.fetch(:question, {}).permit(:title, :body, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ForumOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrap">
      <%= render 'partials/appnav' %>
      <%= yield :jumbotron %>
      <div id="main" class="container pt-4">
        <%= yield %>
      </div>

      <footer class="py-5 bg-primary">
        <div class="container">
          <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
        </div>
        <!-- /.container -->
      </footer>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/index.html.erb
<div class="row mt-3">
  <div class="col-md-3">
    <% if current_user.present? %>
      <%= link_to 'New Question',
              new_question_path,
                  class: 'btn btn-success btn-block mb-3 font-weight-bolder' %>
      <hr>
    <% end %>
    <ul class="list-group">
      <li class="list-group-item border-0">
        <i class="fas fa-star w-25"></i>
        <strong>All Questions</strong>
      </li>
      <li class="list-group-item border-0">
        <i class="fas fa-fire w-25"></i>
        <strong>Popular</strong>
      </li>
      <li class="list-group-item border-0">
        <i class="fas fa-check w-25"></i>
        <strong>Solved</strong>
      </li>
      <li class="list-group-item border-0">
        <i class="fas fa-times w-25"></i>
        <strong>Unsolved</strong>
      </li>
      <li class="list-group-item border-0">
        <i class="fas fa-comment-slash w-25"></i>
        <strong>No Replies</strong>
      </li>
    </ul>
    <hr>
    <ul class="list-group mt-3">
      <% Category.all.each do |c| %>
        <li class="list-group-item border-0">
          <i class="fas fa-folder w-25"></i>
          <strong>
            <%= c.title %>
          </strong>
        </li>
      <% end %>
    </ul>
    <hr>
  </div>

  <div class="col-md-9">
    <% @questions.each do |q| %>
      <div class="card mb-4 rounded-0 border-0">
        <div class="card-body p-0">
          <span class='h4'>
            <%= link_to q.title, q %>
          </span>

          <span class='float-right text-muted'>
            <i class="far fa-comment"></i>
            <%= q.replies_count %>
          </span>
        </div>
        <div class="d-inline">
          <div class="float-left">
            <strong class='d-inline text-info'>
              <%= q.user.username %>
            </strong>
            <span>
              asked <%= time_ago_in_words q.created_at %>
            </span>
          </div>
          <div class="float-right">
            <span class="badge badge-warning">
              <%= q.category.title %>
            </span>
          </div>
        </div>
      </div>
    <% end %>
    <hr>
    <div class='paginator'>
      <%= link_to_prev_page @questions, '« Previous' %>
      <%= link_to_next_page @questions, 'More »' %>
    </div>
  </div>
</div>

app/views/partials/_appnav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <a class="navbar-brand" href="<%= root_path %>">
      <i class="fas fa-users"></i>
      ForumOnRails
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor03">
      <form class="form-inline my-2 my-lg-0 w-100">
        <input class="form-control-sm mr-sm-1 search-input" type="text" placeholder="Search">
        <button class="btn btn-sm btn-secondary my-2 my-sm-0" type="submit">
          <i class="fas fa-search"></i>
        </button>
      </form>
      <ul class="navbar-nav ml-auto ml-md-0">
        <% if current_user %>
          <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-bell fa-fw"></i>
              <span class="badge badge-danger">9+</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-envelope fa-fw"></i>
              <span class="badge badge-danger">7</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-user-circle fa-fw"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
              <a class="dropdown-item" href="#">Settings</a>
              <a class="dropdown-item" href="#">Activity Log</a>
              <div class="dropdown-divider"></div>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :category %>
    <%= collection_select(:question, :category_id, Category.all, :id, :title) %>
  </div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>

  <div class="form-group">
    <%= form.submit 'Submit Question', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<div class="col-md-8 offset-md-2">
    <h1>Editing Question</h1>

    <%= render 'form', question: @question %>

    <%= link_to 'Show', @question %> |
    <%= link_to 'Back', questions_path %>
</div>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>
<%= link_to 'New Question', new_question_path %>

<% @questions.each do |question| %>
  <div class="card mb-5">
    <div class="card-header">
      <%= link_to question.title, question %>
    </div>
    <div class="card-body">
      <%= question.body %>
    </div>
    <div class="card-footer">
      <%= link_to 'Edit', edit_question_path(question) %>
      <span>|</span>
      <%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
<% end %>

app/views/questions/new.html.erb
<div class="col-md-8 offset-md-2">
    <h1>New Question</h1>

    <%= render 'form', question: @question %>

    <%= link_to 'Back', questions_path %>
</div>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<%= @question.title %>

<%= @question.body %>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>